# Generated by Django 3.2.19 on 2023-05-18 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='trip_type',
            field=models.CharField(choices=[('Casual', 'Casual'), ('Business', 'Business'), ('Hiking', 'Hiking'), ('Pleasure', 'Pleasure'), ('Other', 'Other')], default='Casual', max_length=50),
        ),
    ]
